# Generated by Django 2.1a1 on 2018-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weergave',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('timestamp', models.DateField()),
                ('temperature', models.FloatField(blank=True, default=None, null=True)),
                ('humidity', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
